services:
  - type: web
    name: HOTEL MIRAMAR SG
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn project_core.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: HOTEL MIRAMAR SG
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.11.0
