# Generated by Django 4.2.2 on 2023-07-12 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'User Feedback', 'verbose_name_plural': 'User Feedback'},
        ),
    ]
