# Generated by Django 4.2.2 on 2023-07-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0002_alter_contactmessage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourist_spot_name', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='tourist_spots/')),
                ('description', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
    ]
